name: Deploy Hello API

on:
  push:
    branches: [ master, development ]
    tags:
      - '*'
env:
  AWS_DEFAULT_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CONTAINER_IMAGE: sample-api:${{ github.sha }}

jobs:
  Dockerize: 
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2


      - name: Build and tag the image
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          cd examples/sample-api
          go build -ldflags "-linkmode external -extldflags -static" -a -o main
          docker build \
            -t $CONTAINER_IMAGE \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE .

      - name: Push Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE      
  

